<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
// generated by Poedit from ai-price-negotiator-for-woocommerce-en_GB.po, do not edit directly
return ['domain'=>NULL,'plural-forms'=>'nplurals=2; plural=(n != 1);','language'=>'en_GB','pot-creation-date'=>'2025-12-10 02:30+0530','po-revision-date'=>'2025-12-10 02:30+0530','translation-revision-date'=>'2025-12-10 02:30+0530','project-id-version'=>'AI Price Negotiator for WooCommerce','x-generator'=>'Poedit 3.8','messages'=>[]];
